# Continuous Integration setup for Rogue River

language: cpp

sudo: required

cache:
  apt: true
 
matrix:
  include:
    - os: linux
  addons:
    apt:
      sources:
        - ubuntu-toolchain-r-test
      packages:
        - clang-3.7
        - g++-5
        - gcc-5

compiler:  
    - gcc

before_script:
    - sudo unlink /usr/bin/gcc && sudo ln -s /usr/bin/gcc-5 /usr/bin/gcc
    - gcc --version
    - mkdir build
    - cd build
    - cmake ..

script: make
