# Continous integration settings for Windows builds

os: Visual Studio 2015

platform:
    - x86
    - x64

build_script:
    - md build
    - cd build
    - cmake -G "Visual Studio 14 2015 Win64" -DCMAKE_INSTALL_PREFIX=./ ..
    - cmake --build . --config Release
    
after_build:
    - cpack

artifacts:
  - path: 'build\*.zip'
    name: Releases

deploy:
  provider: GitHub
  auth_token:
    secure: 1WeDROrbv0cmMJfVQIANpP6T5IGFfXGTaAcrEYbfkQypeblPFeM1WS6fZiMTE7Z6
  artifact: 'build\*.zip'
  draft: false
  prerelease: false
  on:
    appveyor_repo_tag: true
